import React from 'react';
import "./HomePage.css";
import Product from "./Products";
import Header from "./Header";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from 'react-responsive-carousel';

import Footer from './Footer';
function HomePage() {
 
  return (<>
    <div className='homepage'>
      <Header/><Carousel className="carousel" autoPlay infiniteLoop showStatus={false} showThumbs={false} interval={4000}>
        <img  className="homepage-img" src="https://images-eu.ssl-images-amazon.com/images/G/02/digital/video/merch2016/Hero/Covid19/Generic/GWBleedingHero_ENG_COVIDUPDATE__XSite_1500x600_PV_en-GB._CB428684220_.jpg" alt="BannerImage"/>
        <img  src="https://images-eu.ssl-images-amazon.com/images/G/31/img21/Fashion/Event/AugART/Teaser/PC/revised/V1/FIle-1_PC_01.jpg" alt="BannerImage"/>
        <img  src="https://m.media-amazon.com/images/I/81pXJW9qztL.jpg" alt="BannerImage"/>
        </Carousel>
        <div className='rows'>
        <Product id={1} title={"Apple iPhone 13 Pro"} price={109900} ratting={5} img={"https://m.media-amazon.com/images/I/61rrisp8qiL._SX679_.jpg"} images={"https://m.media-amazon.com/images/I/61jLiCovxVL._SX679_.jpg"} imagefolder={["https://m.media-amazon.com/images/I/61rrisp8qiL._SX679_.jpg","https://m.media-amazon.com/images/I/61jLiCovxVL._SX679_.jpg","https://m.media-amazon.com/images/I/7161nwSVX9L._SX679_.jpg","https://m.media-amazon.com/images/I/81woDMsj8DL._SX679_.jpg","https://m.media-amazon.com/images/I/61Tda9m5UUL._SX679_.jpg"]} description={["15 cm (6.1-inch) Super Retina XDR display with ProMotion for a faster, more responsive feel","Cinematic mode adds shallow depth of field and shifts focus automatically in your videos","Pro camera system with new 12MP Telephoto, Wide and Ultra Wide cameras; LiDAR Scanner; 6x optical zoom range; macro photography; Photographic Styles, ProRes video, Smart HDR 4, Night mode, Apple ProRAW, 4K Dolby Vision HDR recording","12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording","A15 Bionic chip for lightning-fast performance"]}/>
       
        <Product id={2} title={"Apple iPad Pro"} price={67390} ratting={4.5} img={"https://m.media-amazon.com/images/I/81Y5WuARqpS._SX679_.jpg"} images={"https://m.media-amazon.com/images/I/71f1Tva5lHS._SX679_.jpg"} img1={"https://m.media-amazon.com/images/I/81AgqDsrORS._SX679_.jpg"} img2={"https://m.media-amazon.com/images/I/71HYT9gU+KS._SX679_.jpg"} img3={"https://m.media-amazon.com/images/I/61Pe5-yOYIS._SX679_.jpg"} imagefolder={["https://m.media-amazon.com/images/I/81Y5WuARqpS._SX679_.jpg","https://m.media-amazon.com/images/I/71f1Tva5lHS._SX679_.jpg","https://m.media-amazon.com/images/I/81AgqDsrORS._SX679_.jpg","https://m.media-amazon.com/images/I/71HYT9gU+KS._SX679_.jpg","https://m.media-amazon.com/images/I/61Pe5-yOYIS._SX679_.jpg"]} description={["Apple M1 chip for next-level performance","Stunning 27.96 cm (11-inch) Liquid Retina display with ProMotion, True Tone, and P3 wide color","TrueDepth camera system featuring Ultra Wide front camera with Center Stage","12MP Wide camera, 10MP Ultra Wide camera, and LiDAR Scanner for immersive AR","Stay connected with ultrafast Wi-Fi and 4GLTE"]}/>
        <Product id={3} title={"Redmi Note 11T 5G"} price={15999} ratting={4} img={"https://m.media-amazon.com/images/I/41sJ50FH9OL._SX300_SY300_QL70_FMwebp_.jpg"}images={"https://m.media-amazon.com/images/I/71hwZfOz3bL._SX522_.jpg"} imagefolder={["https://m.media-amazon.com/images/I/41sJ50FH9OL._SX300_SY300_QL70_FMwebp_.jpg","https://m.media-amazon.com/images/I/71hwZfOz3bL._SX522_.jpg","https://m.media-amazon.com/images/I/61dtLQrQASL._SX569_.jpg","https://m.media-amazon.com/images/I/71Od5yJbohL._SX569_.jpg"]} description={["Processor: MediaTek Dimensity 810 Octa-core 5G processor based on 6nm process with HyperEngine 2.0 and clock speed up to 2.4GHz;","Display: 6.6 inch FHD+ (2400x1080) Dot display with 90Hz high refresh rate and adaptive refresh rate technology; 240Hz touch sampling rate;","Camera: 50MP High resolution primary camera f/1.8 with 8MP Ultra-wide sensor| 16 MP Front camera","Battery: 5000mAh battery with 33W Pro fast charging support","Memory, Storage : 6GB LPDDR4X RAM | 128GB UFS2.2 Internal storage","Headphones jack:3.5mm,Display type:LCD,Operating system:MIUI 12.5 based on Android 11"]}/>
        <Product id={4} title={"iQOO Z6 Pro 5G"} price={20999} ratting={3.5} img={"https://m.media-amazon.com/images/I/61E4zA32FrL._SX569_.jpg"}images={"https://m.media-amazon.com/images/I/61ST4CMWEKL._SX569_.jpg"} imagefolder={["https://m.media-amazon.com/images/I/61E4zA32FrL._SX569_.jpg","https://m.media-amazon.com/images/I/61ST4CMWEKL._SX569_.jpg","https://m.media-amazon.com/images/I/51NWjN+7FYL._SY606_.jpg","https://m.media-amazon.com/images/I/51ntchMWVeL._SX679_.jpg"]} description={["Snapdragon 778G comes with octa-core processor that adopts the 6nm process and Kryo 670 architecture.","66W FlashCharge","Liquid Cooling system intelligently sense the heat source and adapt the optimal cooling solution, thereby effectively cool down the phone and reduce the CPU temperature by 12 degrees and surface temperature by 3 degree.","Equipped with 64MP triple camera system, 8MP Wide-angle camera, 2MP Macro camera","iQOO Z6 Pro 5G display provides immersive visual experience with true color contrast and a peak brightness of 1300 nits. HDR10+ helps in providing right color tone mapping for each scene. The display offers 90Hz refersh rate and 180Hz Touch Sampling Rate for a smooth touch response","Display type:amoled, Form factor:bar, Human interface input:touch screen"]}/>
        <Product id={5} title={"OnePlus 10 Pro 5G"} price={60999} ratting={3.5} img={"https://m.media-amazon.com/images/I/61mIUCd-37L._SX679_.jpg"} images={"https://m.media-amazon.com/images/I/51C39N9kq8L._SX679_.jpg"} imagefolder={["https://m.media-amazon.com/images/I/61mIUCd-37L._SX679_.jpg","https://m.media-amazon.com/images/I/51C39N9kq8L._SX679_.jpg","https://m.media-amazon.com/images/I/61ZgE4fiD4L._SX569_.jpg","https://m.media-amazon.com/images/I/71H+yV1VwgL._SX569_.jpg"]} description={["Camera: 48MP Main Camera with Sony IMX 789 Lens (OIS enabled), 50MP Ultra-wide angle camera & 8MP Tele photo lens; Front (Selfie) Camera: 32MP; Flash: Dual LED","Camera Features: Hasselblad Camera for Mobile, Nightscape, Ultra HDR, Smart Scene Recognition, Portrait Mode, Pro Mode, Panorama Mode, Tilt-Shift mode, Long Exposure Mode, 150° Wide angle Mode, Dual-View Video, Movie Mode, Xpan Mode, Filters, Super Stable, Video Nightscape, Video HDR, Video Portrait, Focus Tracking, Timelapse","Camera Features: Hasselblad Camera for Mobile, Nightscape, Ultra HDR, Smart Scene Recognition, Portrait Mode, Pro Mode, Panorama Mode, Tilt-Shift mode, Long Exposure Mode, 150° Wide angle Mode, Dual-View Video, Movie Mode, Xpan Mode, Filters, Super Stable, Video Nightscape, Video HDR, Video Portrait, Focus Tracking, Timelapse","Display Features: Nature tone display, Video colour enhancer, Colour personalization, Colour vision enhancement, Auto brightness, Manual brightness, Screen colour temperature, Bright HDR video mode, Night Mode, Multi-brightness colour calibration, Vibrant Colour Effect Pro, Ultra high resolution video","Operating System: Oxygen OS based on Android 12","Processor: Qualcomm Snapdragon 8 Gen 1"]}/>
        </div>
        <div className='rows'>
        <Product id={6} title={"Samsung Galaxy Book2 Intel 12th Gen core i7"} price={74990} ratting={3} img={"https://m.media-amazon.com/images/I/61WvrP9Fz-L._SX679_.jpg"} images={"https://m.media-amazon.com/images/I/61Dw+0uVfvL._SX425_.jpg"} imagefolder={["https://m.media-amazon.com/images/I/61WvrP9Fz-L._SX679_.jpg","https://m.media-amazon.com/images/I/61Dw+0uVfvL._SX425_.jpg","https://m.media-amazon.com/images/I/61G9+8JxbDL._SX569_.jpg","https://m.media-amazon.com/images/I/61HVYZ9qccL._SX569_.jpg"]} description={["Processor & Memory: Intel, Core_i7_2.7_GHz, Intel® Core„¢ i7-1255U Processor, 4.4 GHz, 16GB RAM,","Operating System & Software: Windows 11 Home operating system, Windows 11 Home Included","Storage: SSD, 512 GB","Display: 15.6 inches, LED display, 1920 X 1080 (FHD) resolution","Ports & Connectivity: 1, HDMI Ports, with Bluetooth;Wi-Fi","Features: Integrated graphics, Intel Iris Xe Graphics"]}/>
        <Product id={7} title={"Samsung S22 Ultra Chrome Finish 2"} price={99999} ratting={5} img={"https://www.reliancedigital.in/medias/Samsung-Galaxy-S22-Ultra-SmartPhone-492849216-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wyNjA4MjF8aW1hZ2UvanBlZ3xpbWFnZXMvaDc3L2hmMi85Nzc5NTIyNjMzNzU4LmpwZ3xlN2Y0MTYzMmNlNzU3NGE1ZDU0YzVlMjU2ZDZiZWZhZGE4NTA4ZTk0NDY2Y2MwMTU0ZDhmOTJlYTk1NTU0MWYw"} images={"https://www.reliancedigital.in/medias/Samsung-Galaxy-S22-Ultra-SmartPhone-492849216-i-2-1200Wx1200H?context=bWFzdGVyfGltYWdlc3w5NTE1MnxpbWFnZS9qcGVnfGltYWdlcy9oYmQvaDlhLzk3Nzk1MjMyODkxMTguanBnfGEyYmZkNTYyNDlhZmE3NTBiZDUyZjUwZTVhMTE2YzI2YTc1NTllOGVjZjFlN2IzYTQ0ZTU3ZmUxMTNkM2E3MWU"} imagefolder={["https://www.reliancedigital.in/medias/Samsung-Galaxy-S22-Ultra-SmartPhone-492849216-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wyNjA4MjF8aW1hZ2UvanBlZ3xpbWFnZXMvaDc3L2hmMi85Nzc5NTIyNjMzNzU4LmpwZ3xlN2Y0MTYzMmNlNzU3NGE1ZDU0YzVlMjU2ZDZiZWZhZGE4NTA4ZTk0NDY2Y2MwMTU0ZDhmOTJlYTk1NTU0MWYw","https://www.reliancedigital.in/medias/Samsung-Galaxy-S22-Ultra-SmartPhone-492849216-i-2-1200Wx1200H?context=bWFzdGVyfGltYWdlc3w5NTE1MnxpbWFnZS9qcGVnfGltYWdlcy9oYmQvaDlhLzk3Nzk1MjMyODkxMTguanBnfGEyYmZkNTYyNDlhZmE3NTBiZDUyZjUwZTVhMTE2YzI2YTc1NTllOGVjZjFlN2IzYTQ0ZTU3ZmUxMTNkM2E3MWU","https://m.media-amazon.com/images/I/71esKKaTf8L._SX569_.jpg","https://m.media-amazon.com/images/I/71D4R3gRKjL._SX569_.jpg"]} description={["The first Galaxy S with embedded S Pen. Write comfortably like pen on paper, turn quick notes into legible text and use Air Actions to control your phone remotely. Improved latency in Samsung Notes makes every pen stroke feel as natural as ink on paper — and you can convert those hastily written ideas into legible text.","5G Ready powered by Galaxy’s first 4nm processor. Our fastest, most powerful chip ever. That means, a faster CPU and GPU compared to Galaxy S21 Ultra. It’s an epic leap for smartphone technology.","The Dynamic AMOLED 2x display improves outdoor visibility with up to 1750 nits in peak brightness.* And the 120Hz adaptive refresh rate keeps the scroll smooth, adjusting to what's on screen for an optimized view.","Our most advanced Pro-grade Camera yet, packing the power of a professional's kit in one handheld device. Also lets you make your nights epic with Nightography: The sensor pulls in more light, the Super Clear Lens tones down lens flare, and fast-acting AI delivers near-instant intelligent processing.","Connector type: usb type c"]}/>
        <Product id={8} title={"Samsung Galaxy Watch5 Bluetooth"} price={30900} ratting={2.5} img={"https://www.favobliss.com/image/cache/catalog/samsung-galaxy-watch5-smart-watch-bluetooth-graphite-1000x1000.jpg"} images={"https://www.jiomart.com/images/product/original/493177539/samsung-galaxy-watch-5-bluetooth-smart-watch-with-3-04-cm-1-2-inch-display-graphite-digital-o493177539-p593573630-1-202209012208.jpeg"} imagefolder={["https://www.favobliss.com/image/cache/catalog/samsung-galaxy-watch5-smart-watch-bluetooth-graphite-1000x1000.jpg","https://m.media-amazon.com/images/I/61Guilj8MEL._SX679_.jpg","https://m.media-amazon.com/images/I/611B5GfWeWL._SX679_.jpg","https://m.media-amazon.com/images/I/61XmNBJTyNL._SX679_.jpg"]} description={["Sleep Tracking: Know your sleep with our new and improved sleep tracking technology. Plan your bedtime, detect snoring, understand and track your sleep.","Body composition Analysis (BIA Measurement): Monitor everything from body fat percentage (BIA) to skeletal muscle weight. All the feedback you need to track your progress.","Optical Heart Rate Sensor: Monitor your heart rate and track your cardiovascular health","Fitness Tracking: Every step counts. Your watch will automatically detect physical activity — counting your steps, calories, and even your routines. (supports over 90 exercises).","Meet the Sapphire crystal display.Water-resistant, with a harder front display made with premium Sapphire Crystal that's 1.6 times stronger against scratches."]} />
        <Product id={9} title={"HP Pavilion Aero AMD Ryzen 5"} price={70900} ratting={2} img={"https://m.media-amazon.com/images/I/71mX6qUGIIL._SX679_.jpg"} images={"https://m.media-amazon.com/images/I/81VFkaN9usL._SX569_.jpg"} imagefolder={["https://m.media-amazon.com/images/I/71mX6qUGIIL._SX679_.jpg","https://m.media-amazon.com/images/I/81VFkaN9usL._SX569_.jpg","https://m.media-amazon.com/images/I/81-l5oLdMnL._SX569_.jpg","https://m.media-amazon.com/images/I/71AOordU9XL._SX569_.jpg"]} description={["Processor & Memory: AMD, ryzen_7, Ryzen 7-5800U, 4.4 GHz, 16GB RAM,","Operating System & Software: Windows 11 Home operating system, McAfee LiveSafe„¢ Included","Storage: SSD, 1 GB","Display: 13.3 inches, LED display, 1920 X 1200 (WUXGA) resolution","Ports & Connectivity: 2 USB 3.0 Ports1, HDMI Ports, with Bluetooth;Wi-Fi","Features: Integrated graphics, AMD Radeon Graphics, 10.5 hours average battery life"]}/>
        </div>
        <div className='rows'>
        <Product id={10} title={"JBL Pulse 4 Speaker Black Colour"} price={16999} ratting={4} img={"https://m.media-amazon.com/images/I/71XRDYZChLL._SY450_.jpg"} images={"https://m.media-amazon.com/images/I/61HXIajZwhL._SX569_.jpg"} imagefolder={["https://m.media-amazon.com/images/I/61HXIajZwhL._SX569_.jpg","https://m.media-amazon.com/images/I/71XRDYZChLL._SY450_.jpg","https://m.media-amazon.com/images/I/81N4q+avPWL._SX679_.jpg","https://m.media-amazon.com/images/I/91n9PThjCpL._SX679_.jpg"]} description={["High-resolution 360-degree LED Lightshow","Wireless Bluetooth Streaming","12 hours of Playtime","360 degree Lightshow and Sound","IPX7 Waterproof","IP67 water-resistant and dust-resistant: Engineered to withstand splashes and sand."]}/>
        <Product id={11} title={"HP Pavilion Gaming 5th Gen AMD"} price={66999} ratting={3} img={"https://images-eu.ssl-images-amazon.com/images/I/412hYHFcGjL._SX300_SY300_QL70_FMwebp_.jpg"} images={"https://m.media-amazon.com/images/I/718H1G8-MsL._SX569_.jpg"} imagefolder={["https://images-eu.ssl-images-amazon.com/images/I/412hYHFcGjL._SX300_SY300_QL70_FMwebp_.jpg","https://m.media-amazon.com/images/I/718H1G8-MsL._SX569_.jpg","https://m.media-amazon.com/images/I/71xenytencL._SX569_.jpg","https://m.media-amazon.com/images/I/71ICN+rxOtL._SX569_.jpg"]} description={["Processor & Memory: AMD, ryzen_5, Ryzen 5-5600H, 4.2 GHz, 8GB RAM,RAM Expandable up to 16GB","Operating System & Software: Windows 10 Home operating system, Preinstalled Microsoft Office Home & Student 2019 Included","Storage: SSD, 512 GB","Display: 15.6 inches, LED display, 1920 X 1080 (FHD) resolution","Ports & Connectivity: 2 USB 3.0 Ports1, HDMI Ports","Features: Dedicated graphics, NVIDIA GeForce GTX 1650, 4 GB Graphics RAM, 4 hours average battery life","Warranty: 1 year manufacturer warranty on the device from the date of purchase. In case of any technical/product related queries, please call 1800-258-7170 or 1860-258-3079"]}/>
        <Product id={12} title={"Sony Bravia 139 cm (55 inches) 4K Ultra HD"} price={60999} ratting={4.5} img={"https://m.media-amazon.com/images/I/71ZKGDdz1lL._SX450_.jpg"} images={"https://m.media-amazon.com/images/I/41Nh0LWgqCL._SY300_SX300_QL70_FMwebp_.jpg"} imagefolder={["https://m.media-amazon.com/images/I/71ZKGDdz1lL._SX450_.jpg","https://m.media-amazon.com/images/I/41Nh0LWgqCL._SY300_SX300_QL70_FMwebp_.jpg","https://m.media-amazon.com/images/I/71NVKOYiO+L._SX679_.jpg","https://m.media-amazon.com/images/I/81FywN6BXsL._SX679_.jpg"]} description={["Resolution: 4K Ultra HD (3840 x 2160) | Refresh Rate: 60 Hertz | 178 Degree wide viewing angle","Connectivity: 4 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices","Sound : 20 Watts Output | X Balanced Speaker| Dolby Atmos | Clear Phase | Sound Ambient Optimization","Smart TV Features: Google TV | Watchlist | Ok Google | Google Play | Chromecast | Built In Mic | BRAVIA CAM Support | Video Call | Additional Features: Apple Airplay | Apple Homekit |Alexa","Display: X1 4K HDR Processor | 4K HDR | Triluminos Pro| Dolby Vision | 4K X Reality Pro | Motion Flow XR200 | ALLM (Auto Low Latency Mode)","Warranty Information: 1 year warranty provided by the manufacture from the date of purchase",]}/>
        <Product id={13} title={"Mi 189.34cm (75 inches) Q1 Series"} price={126999} ratting={3.5} img={"https://m.media-amazon.com/images/I/71fZOKh0i1L._SY450_.jpg"} images={"https://m.media-amazon.com/images/I/71qgxrIJe0L._SX425_.jpg"} imagefolder={["https://m.media-amazon.com/images/I/71fZOKh0i1L._SY450_.jpg","https://m.media-amazon.com/images/I/71qgxrIJe0L._SX425_.jpg","https://m.media-amazon.com/images/I/71QvOYXZMYL._SX679_.jpg","https://m.media-amazon.com/images/I/81cyu0xbxRL._SX679_.jpg"]} description={["Resolution : 4K Ultra HD (3840 x 2160) Resolution | Refresh Rate : 120Hz | 178 Degree wide viewing angle","Connectivity: 3 HDMI ports to connect latest gaming consoles, set top box, Blu-ray Players | 2 USB ports to connect hard drives and other USB devices | ALLM | eARC - Dolby Atmos Passthrough eARC HDMI port | Bluetooth 5.0 | Optical","Sound: 30 Watts Output with 6 Speakers setup | Dolby Audio | DTS-HD | Dolby Atmos pass through eARC","Smart TV Features : Android TV 10 | PatchWall 4 with IMDb integration | Kids Mode with Parental Lock | 75+ Free Live Channels | Universal search | Language Universe (16+ Languages) | India's Top 10 | Miracast | Supported Apps: Prime Video | Netflix | Disney + Hotstar | YouTube | Apple TV | 5000+ apps from Play Store | Quad core processor | Built-in Wi-Fi | Chromecast built-in | Ok Google | Auto Low Latency Mode | 2GB RAM + 32GB Storage | Hands-free Google Assistant","Display: Quantum Dot Display | Premium Metal Bezel-less Design | Full Array Local Dimming | Vivid Picture Engine | Dolby Vision | HDR10+ | HLG | 100% Color Volume | 95% DCI-P3 | MEMC","Warranty Information: 1 year comprehensive warranty on product and 1 year additional on Panel provided by the brand from the date of purchase"]}/>
        </div>
       
       
    </div><Footer/>
    </>


  )

  }
export default HomePage